<!DOCTYPE html>
<html>

<head>
  <title>Responsive Shopping Cart In Bootstrap 4</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="../css/cart.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
  <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
</head>

<body>
  <div class="container-fluid text-dark bg-white pb-2 mb-3 mt-5 testando ">
    <div class="row p-4 bg-mobile">
      <div class="col-md-12 col-sm-12">
        <h2 id="tituloCart" class="text-success">Detalhes do pedido</h2>
      </div>
      <div class="col-12" id="divDosBotoes">
        <div class="row" id="botoesCompra">
          <div class="col-xl-1 col-md-2 col-sm-2 col-3 col-lg-1">
            <a href="../index.html"><button type="button" class="btn btn-custom pull-right btn-custom">Voltar</button></a>
          </div>
          <div class="col-xl-11 col-md-10 col-sm-10 col-9 col-lg-11">
            <button type="button" class="btn btn-custom pull-right btn-custom">Finalizar</button>
          </div>
        </div>
      </div>
    </div>
    <div class="row p-3 effects">
      <div class="col-md-3">
        <img src="../img/frango_parmegiana-600x400.jpg" class="img-responsive">
      </div>
      <div class="col-md-3">
        <h4>Costela</h4>
        <h5>$500</h5>
     
      </div>
      
      <div class="col-md-3">
        <h3 class="text-info">Quantidade: <span class="text-danger">2</span></h3>
        <div class="color-group">
            <a href="#" ></a>
            <a href="#" ></a>
            <a href="#" ></a>
            <a href="#" ></a>
            <a href="#" ></a>
        </div>
      </div>
      <div class="col-md-3">
        <a href="#"><i class="fa fa-edit"></i></a>
        <a href="#"><i class="fas fa-trash-alt"></i></a>
      </div>
    </div>
    <div class="row p-3 effects">
      <div class="col-md-3">
        <img src="../img/Batata-Sauté-Batatas-Salteadas-na-Manteiga.jpg" class="img-responsive">
      </div>
      <div class="col-md-3">
        <h4>Batatas salteadas</h4>
        <h5>$500</h5>

      </div>
      <div class="col-md-3">
        <h3 class="text-info">Quantidade: <span class="text-danger">2</span></h3>
        <div class="color-group">
            <a href="#" ></a>
          <a href="#" ></a>
          <a href="#" ></a>
          <a href="#" ></a>
          <a href="#" ></a>
        </div>
      </div>
      <div class="col-md-3">
        <a href="#"><i class="fa fa-edit"></i></a>
        <a href="#"><i class="fas fa-trash-alt"></i></a>
      </div>
    </div>
    <div class="row p-3 effects">
      <div class="col-md-3">
        <img src="../img/Tainha-Assada-20-610x300.jpg" class="img-responsive">
      </div>
      <div class="col-md-3">
        <h4>Tainha ao alho e óleo</h4>
        <h5>$500</h5>
      </div>
      <div class="col-md-3">
        <h3 class="text-info">Quantidade: <span class="text-danger">2</span></h3>
        <div class="color-group">
          <a href="#" ></a>
          <a href="#" ></a>
          <a href="#" ></a>
          <a href="#" ></a>
          <a href="#" ></a>
        </div>
      </div>
      <div class="col-md-3">
        <a href="#"><i class="fa fa-edit"></i></a>
        <a href="#"><i class="fas fa-trash-alt"></i></a>
      </div>
    </div>
  </div>
</body>

</html>