<!DOCTYPE html>
<html>

<head>
  <title>Responsive Shopping Cart In Bootstrap 4</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="../css/cart.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
  <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
</head>

<body>
  <div class="container-fluid text-dark bg-white pb-2 mb-3 mt-5 testando ">
    <div class="row p-4 bg-mobile">
      <div class="col-md-12 col-sm-12">
        <h2 id="tituloCart" class="text-success">Detalhes do pedido</h2>
      </div>
      <div class="col-12" id="divDosBotoes">
        <div class="row" id="botoesCompra">
          <div class="col-xl-1 col-md-2 col-sm-2 col-3 col-lg-1">
            <a href="../index.html"><button type="button" class="btn btn-custom pull-right btn-custom">Voltar</button></a>
          </div>
          <div class="col-xl-11 col-md-10 col-sm-10 col-9 col-lg-11">
           <a href="/cartlimpar/"><button type="button" class="btn btn-custom pull-right btn-custom">Finalizar</button></a>
          </div>
        </div>
      </div>
    </div>





    <?php


    foreach ($_SESSION['produtos'] as $key => $value) {

      echo "<div class='row p-3 effects'>";
        echo "<div class='col-md-3'>";
        echo "<img src='" . $value[0]['imgProduto'] . "' class='img-responsive'>";
        echo "</div>";
        echo "<div class='col-md-3'>";
        echo "<h4>" . $value[0]['nomeProduto'] . "</h4>";
        echo "</div>";
        echo "<div class='col-md-3'>";
        ;
        echo "<h5>" . $value[0]['precoProduto'] . "</h5>";
                echo "</div>";
        echo "<div class='color-group'>";
        echo "</div>";
      echo "</div>";
    }
    ?>

  </div>
</body>

</html>