<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="/fontawesome/css/solid.min.css">
    <link rel="stylesheet" href="/css/style.css">


    <title>Gourmeet - Cardápio</title>
</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <div id="fora" class="col-sm-5 col-md-6 col-lg-5 col-xl-5">

                <div class="row text-white cardapio">
                    <div class="col-12 m-2 pb-3 pt-3 pr-2 menu">
                        <a href="/">
                            <h1 class="titulo">Cardápio</h1>
                        </a>

                    </div>

                    <?php
                    foreach ($categorias as $key => $value) {
                        echo "<div class='col-12 menus'>";
                        echo "<a href='/" . $value['idCategoria'] . "'>";
                        echo "<h4 class='p-3'>";
                        echo $value['nomeCategoria'];
                        echo "</h4>";
                        echo "</a>";
                        echo "</div>";
                    }
                    ?>
                </div>
            </div>


            <!-- div da imagens e descrição dos pratos -->
            <div id="cardapio2" class="col-sm-7 col-md-6 col-lg-7 col-xl-7">
                <div class="row">
                    <div class="col-12" id="pratos">
                        <div class="col-12 pt-5">
                            <?php
                                echo  "<h1 class='titulo'>".$categoriaAtual[0]['nomeCategoria']."</h1>";
                            ?>

                            <a href="cart/">
                                <i class="fas fa-shopping-cart mr-5"></i>
                            </a>

                            <div class="row">
                                <div class="col-12 p-3 pt-5">
                                    <div class="row">
                                        <?php
                                        foreach ($produtos as $key => $value) {

                                            echo "<div class='col-4 p-1'>";
                                            echo "<img class='imagensComidas pb-4' src='" . $value['imgProduto'] . "'>";
                                            echo "</div>";
                                            echo "<div class='col-8'>";
                                            echo "<h3>";
                                            echo $value['nomeProduto'];
                                            echo "</h3>";
                                            echo "<p>";
                                            echo $value['descProduto']."Lorem ipsum dolor sit amet, sunt in culpa qui officia deserunt mollit anim id est laborum.";
                                            echo "</p>";
                                            echo "</div>";
                                            echo "<div class='col-12 botao pb-5'>";
                                            echo "<label class= 'mr-4'>";
                                            echo "R$ " . $value['precoProduto'];
                                            echo "</label>";
                                            echo "<button type='button' class='btn btn-primary '>";
                                            echo "Adicionar";
                                            echo "</button>";
                                            echo "</div>";
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</body>

<script src="vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="vendor/bootstrap/css/bootstrap.min.css"></script>
<script src="vendor/fontawesome/css/fontawesome.min.css"></script>

</html>