
<!DOCTYPE html>
<html>
<head>
<title>Fascinating Checkout Form Flat Responsive Widget Template :: w3layouts</title>
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Fascinating Checkout Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
<link href="/css/payment.css" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="/css/creditly.css" type="text/css" media="all" />
<link rel="stylesheet" href="/css/easy-responsive-tabs.css">
<script src="/jquery/jquery.min.js"></script>
<link href="//fonts.googleapis.com/css?family=Overpass:100,100i,200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext" rel="stylesheet">
</head>
<body>
	<div class="main">	
		<h1>Checkout</h1>
		<div class="w3_agile_main_grids">
			<div class="agile_main_top_grid">
				
				<div class="wthree_total">
					<h2>Total: </h2>
					<?
						 print($_SESSION['totalCompra']);
						 exit();
					?>
					
				</div>
			</div>
			<div class="agileinfo_main_bottom_grid">
				<div id="horizontalTab">
					<ul class="resp-tabs-list">
						<li><img src="/img/1.jpg" alt=" " /></li>
						<li><img src="/img/2.jpg" alt=" " /></li>
					</ul>
					<div class="resp-tabs-container">
						<div class="agileits_w3layouts_tab1">
							<form action="#" method="post" class="creditly-card-form agileinfo_form">
								<section class="creditly-wrapper wthree, w3_agileits_wrapper">
									<div class="credit-card-wrapper">
										<div class="first-row form-group">
											<div class="controls">
												<label class="control-label">Nome no cartão</label>
												<input class="billing-address-name form-control" type="text" name="name" placeholder="João da Silva">
											</div>
											<div class="w3_agileits_card_number_grids">
												<div class="w3_agileits_card_number_grid_left">
													<div class="controls">
														<label class="control-label">Número no cartão</label>
														<input class="number credit-card-number form-control" type="text" name="number"
																	  inputmode="numeric" autocomplete="cc-number" autocompletetype="cc-number" x-autocompletetype="cc-number"
																	  placeholder="1111 1111 1111 1111 ">
													</div>
												</div>
												<div class="w3_agileits_card_number_grid_right">
													<div class="controls">
														<label class="control-label">CVV</label>
														<input class="security-code form-control"Â·
																	  inputmode="numeric"
																	  type="text" name="security-code"
																	  placeholder="123">
													</div>
												</div>
												<div class="clear"> </div>
											</div>
											<div class="controls">
												<label class="control-label">Validade</label>
												<input class="expiration-month-and-year form-control" type="text" name="expiration-month-and-year" placeholder="MM / YY">
											</div>
										</div>
										<button class="btn btn-light"><span>Pagar</span></button>
									</div>
								</section>
							</form>
						</div>
						<div class="agileits_w3layouts_tab2">
							<h3>Não possui uma conta no paypal? <a href="https://www.paypal.com/welcome/signup/#/email_password">Registrar</a></h3>
							<form action="#" method="post">
								<label class="agileits_label">Seu email</label>
								<input type="email" name="Email" placeholder="w3layouts@example.com" required="">
								<label class="agileits_label">Senha</label>
								<input type="password" name="Password" placeholder="Password" required="">
								<input type="submit" value="Login">
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="agileits_copyright">
			<p>Situação de aprendizagem Senai Blumenau | Desenvolvido por Christian Schoeller Bernardo Schramm e Brian Lueders </p>
		</div>
	</div>
	<!-- credit-card -->
		<script type="text/javascript" src="/jquery/creditly.js"></script>
		<script type="text/javascript">
			$(function() {
			  var creditly = Creditly.initialize(
				  '.creditly-wrapper .expiration-month-and-year',
				  '.creditly-wrapper .credit-card-number',
				  '.creditly-wrapper .security-code',
				  '.creditly-wrapper .card-type');

			  $(".creditly-card-form .submit").click(function(e) {
				e.preventDefault();
				var output = creditly.validate();
				if (output) {
				  // Your validated credit card output
				  console.log(output);
				}
			  });
			});
		</script>
	<!-- //credit-card -->
	<!-- tabs -->
	<script src="/jquery/easy-responsive-tabs.js"></script>
	<script>
		$(document).ready(function () {
			$('#horizontalTab').easyResponsiveTabs({
				type: 'default', //Types: default, vertical, accordion           
				width: 'auto', //auto or any width like 600px
				fit: true,   // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				activate: function(event) { // Callback function if tab is switched
				var $tab = $(this);
				var $info = $('#tabInfo');
				var $name = $('span', $info);
				$name.text($tab.text());
				$info.show();
				}
			});
		});
	</script>
	<!-- //tabs -->
</body>
</html>